test_pod:
  enabled: true
  image: bats/bats:1.8.2
  pullPolicy: IfNotPresent
memberlist:
  service:
    publishNotReadyAddresses: true
loki:
  enabled: true
  isDefault: true
  image:
    tag: 2.9.3
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
    failureThreshold: 300
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
    failureThreshold: 300
  datasource:
    jsonData: "{}"
    uid: ""
promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
fluent-bit:
  enabled: false
