apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit
  namespace: kube-system
rules:
  - apiGroups: ["*"]
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentbit
roleRef:
  kind: ClusterRole
  name: fluentbit
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentbit
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: kube-system
  labels:
    app: fluentbit
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      tolerations:
        - key: dedicated
          value: app
          effect: NoSchedule
      serviceAccountName: fluentbit
      containers:
        - name: fluentbit
          image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
          ports:
            - containerPort: 2020
              name: api
            - containerPort: 24224
              name: forward
          volumeMounts:
            - name: varlog
              mountPath: /var/log/pods
            - name: config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log/pods
        - name: config
          configMap:
            name: fluentbit-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name        tail
        Path        /var/log/pods/*product*/app/0.log
        Parser      docker
        Tag         product

    [INPUT]
        Name        tail
        Path        /var/log/pods/*customer*/app/0.log
        Parser      docker
        Tag         customer

    [OUTPUT]
        Name cloudwatch_logs
        Match product
        region ap-northeast-2
        log_group_name /wsi/webapp/product
        log_stream_prefix logs-
        auto_create_group true

    [OUTPUT]
        Name cloudwatch_logs
        Match customer
        region ap-northeast-2
        log_group_name /wsi/webapp/customer
        log_stream_prefix logs-
        auto_create_group true

  parsers.conf: |
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y/%m/%d - %H:%M:%S
        Time_Keep On
        Decode_Field_As   escaped_utf8    log