apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: product
  namespace: wsi
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product
  minReplicaCount: 2
  maxReplicaCount: 12
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "40"
        containerName: product