kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  flb_log_cw: "false"  # Set to true to ship Fluent Bit process logs to CloudWatch.

  filters.conf: |
    [FILTER]
        Name parser
        Match kube.*
        Key_name log
        Parser docker

  output.conf: |
    [OUTPUT]
        Name cloudwatch_logs
        Match *token*
        region ap-northeast-2
        log_group_name /aws/app/token
        log_stream_prefix logs-
        log_retention_days 60
        auto_create_group true

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y/%m/%d - %H:%M:%S
        Decode_Field_As escaped_utf8 log