apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: product-instrumentation
  namespace: wsi
spec:
  exporter:
    endpoint: http://otel-collector-collector.otel:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  go:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector-collector.otel:4318