apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          args:
            - /bin/sh
            - -c
            - |
              echo 'server {
                  listen 80;
                  location /nginx_status {
                      stub_status;
                      allow all;
                  }
              }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
      #topologySpreadConstraints:
      #- maxSkew: 1
      #  topologyKey: "topology.kubernetes.io/zone"
      #  whenUnsatisfiable: DoNotSchedule
      #  matchLabelKeys:
      #    - pod-template-hash
      #  labelSelector:
      #    matchLabels:
      #      app: nginx
