apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  parentRefs:
    - name: wsi
      namespace: wsi
      sectionName: http
  rules:
    - backendRefs:
        - name: grafana
          kind: Service
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
  name: grafana
  namespace: monitoring
spec:
  targetRef:
    group: ""
    kind: Service
    name: grafana
  protocol: HTTP
  protocolVersion: HTTP1
  healthCheck:
    enabled: true
    intervalSeconds: 5
    timeoutSeconds: 5
    healthyThresholdCount: 3
    unhealthyThresholdCount: 2
    path: "/"
    port: 3000
    protocol: HTTP
    protocolVersion: HTTP1
    statusMatch: "200"
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: grafana
  namespace: monitoring
spec:
  serviceRef:
    name: grafana
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:658986583341:targetgroup/grafana/eb87319766d8ca7c
