apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: app
spec:
  ##### maxPods로 Pod 개수를 지정 #####
  kubelet:
    maxPods: 7
  amiFamily: Bottlerocket  # AL2023 | Bottlerocket
  role: "karpenter-skills-eks-cluster-20250309055904465800000009"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "skills-eks-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "skills-eks-cluster"
  amiSelectorTerms:
    - id: "ami-028b4fee2629dc99c"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 8Gi
        volumeType: gp3
        iops: 2000
  tags:
    Name: skills-eks-addon-node
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: app
spec:
  template:
    metadata:
      labels:
        dedicated: app
    spec:
      taints:
        - key: dedicated
          value: app
          effect: NoSchedule
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t4g"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t4g.small"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: app
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m