singleNode: true
replicas: 1
discovery:
  type: single-node

plugins:
  security:
    disabled: true
    ssl:
      http:
        enabled: false

persistence:
  storageClass: 'gp2'
  size: '2Gi'

resources:
  requests:
    cpu: "200m"
    memory: "100Mi"

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "Worldskills!Korea1"
  - name: plugins.security.ssl.http.enabled
    value: "false"