apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
  namespace: wsi
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: product
  namespace: wsi
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: secretstore
  target:
    name: product
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: product